export const GET_HOTEL_DESCRIPTION_REQUEST = "GET_HOTEL_DESCRIPTION_REQUEST";
export const GET_HOTEL_DESCRIPTION_SUCCESS = "GET_HOTEL_DESCRIPTION_SUCCESS";
export const GET_HOTEL_DESCRIPTION_FAIL = "GET_HOTEL_DESCRIPTION_FAIL";
