export const GET_LOCATIONS_BY_NAME_REQUEST = "GET_LOCATIONS_BY_NAME_REQUEST";
export const GET_LOCATIONS_BY_NAME_SUCCESS = "GET_LOCATIONS_BY_NAME_SUCCESS";
export const GET_LOCATIONS_BY_NAME_FAIL = "GET_LOCATIONS_BY_NAME_FAIL";
